version: "3.9"

services:
  db:
    image: postgres
    container_name: learn_pg
    environment:
      POSTGRES_DB: learnsystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: learn_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: learn_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:secret@db:5432/learnsystem
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: dev-secret
      JWT_ALGORITHM: HS256
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

volumes:
  pg_data:
